name: Cypress Tests

on:
  workflow_call:
    inputs:
      test_suite:
        required: true
        type: string
        description: targetted test_suite
      dispatcher_text:
        required: true
        type: string
        description: 'Enter your name to dispatch workflow manually'
        default: 'Harry Potter'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Dependencies
        run: npm install

      - name: Cypress Run Triggered by ${{ inputs.dispatcher_text }}
        run: npm run ${{ inputs.test_suite }}
