name: Cypress Tests

on:
  workflow_call:
    inputs:
      url: 
        required: true
        type: string
        description: targeted site
      test_suite:
        required: true
        type: string
        description: targetted test_suite
      dispatcher_text:
        required: true
        type: string
        description: 'Enter your name to dispatch workflow manually'
        default: 'Harry Potter'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.GITHUB_BOT_KEY }}
          repository: bdle/cy-mortgage-calulator

      - name: Install Dependencies
        run: npm install

      - name: Cypress Run Triggered by ${{ inputs.dispatcher_text }}
        run: |
          CYPRESS_BASE_URL=${{ inputs.url }} \
          npm run ${{ inputs.test_suite }}
